export const copy = {
	ar: {
		global: {
			brand: "FITWAY",
			languageAction: "English",
			languageSwitchLabel: "التبديل إلى اللغة الإنجليزية",
			skip: "تخطي إلى المحتوى الرئيسي",
		},
		review: {
			title: "فهرس مراجعة FITWAY",
			description: "افتح كل مسار وحالة ولغة ومقاس شاشة من مكان واحد.",
			publicGroup: "الواجهة العامة",
			staffGroup: "عمليات الموظفين",
			ownerGroup: "مساحة المالك",
			route: "المسار",
			state: "الحالة",
			language: "اللغة",
			viewport: "مقاس الشاشة",
			open: "فتح الشاشة",
			live: "مباشر",
			loading: "تحميل",
			stale: "متأخر",
			unavailable: "غير متاح",
			closed: "مغلق",
			error: "خطأ",
			login: "دخول الموظفين",
			staffLive: "العمليات المباشرة",
			analytics: "التحليلات",
			history: "السجل",
			settings: "الإعدادات",
			access: "إدارة الوصول",
			audit: "سجل التدقيق",
			health: "الصحة والتشغيل",
			desktop: "سطح المكتب",
			tablet: "الجهاز اللوحي",
			mobile: "الجوال",
		},
		public: {
			bands: {
				quiet: "هادئ",
				moderate: "متوسط",
				busy: "مزدحم",
				packed: "ممتلئ جدًا",
			},
			live: {
				open: "النادي مفتوح الآن",
				freshness: "تحديث مباشر",
				updated: "آخر تحديث 2:59 م",
				relative: "قبل 30 ثانية",
				combinedFreshness: "تحديث مباشر · آخر تحديث 2:59 م · قبل 30 ثانية",
				crowdLabel: "مستوى الازدحام",
				crowdValue: "متوسط",
				countLabel: "العدد التقريبي",
				currentLevel: "المستوى الحالي",
				signalLabel: "إشارة مستوى الازدحام",
				signalSummary:
					"مستوى الازدحام الحالي متوسط. تم الوصول إلى هادئ، ومتوسط هو المستوى الحالي، والمستويات الأعلى لم تُسجّل بعد.",
				summary:
					"النادي مفتوح الآن. مستوى الازدحام: متوسط. العدد التقريبي: 37. تحديث مباشر. آخر تحديث 2:59 م، قبل 30 ثانية.",
			},
			loading: {
				label: "جارٍ تحميل حالة النادي",
				summary: "جارٍ تحميل أحدث حالة للنادي.",
			},
			stale: {
				status: "التحديثات المباشرة متأخرة",
				crowdLabel: "آخر مستوى ازدحام معروف",
				countLabel: "آخر عدد تقريبي معروف",
				freshness: "آخر تحديث معروف",
				updated: "آخر تحديث معروف 3:00 م",
				relative: "قبل 5 دقائق",
				warning: (count, time) =>
					`كان آخر عدد تقريبي معروف ${count} في ${time}. التحديثات المباشرة متأخرة.`,
				summary: (band, count, time) =>
					`التحديثات المباشرة متأخرة. آخر مستوى ازدحام معروف: ${band}. آخر عدد تقريبي معروف: ${count}. آخر تحديث ${time}.`,
			},
			unavailable: {
				eyebrow: "حالة النادي الآن",
				title: "التحديث المباشر غير متاح الآن",
				body: "لا نعرض عددًا قديمًا على أنه مباشر. يرجى المحاولة مرة أخرى لاحقًا.",
				summary: "لا تتوفر حاليًا معلومات إشغال يمكن الاعتماد عليها.",
			},
			closed: {
				status: "مغلق الآن",
				title: "مغلق الآن",
				opensAt: (time) => `يفتح ${time}`,
				summary: (time) => `النادي مغلق الآن. يفتح اليوم الساعة ${time}.`,
			},
			error: {
				eyebrow: "حالة النادي الآن",
				title: "تعذر تحميل حالة النادي",
				body: "حدث خطأ أثناء جلب أحدث حالة. حاول مرة أخرى.",
				retry: "إعادة المحاولة",
				retrying: "جارٍ إعادة المحاولة",
				summary: "تعذر تحميل حالة النادي. تتوفر إمكانية إعادة المحاولة.",
			},
		},
		login: {
			title: "دخول مكتب الاستقبال",
			description: "أدخل رمز الدخول المشترك لفتح لوحة العمليات.",
			pinLabel: "رمز الدخول",
			pinPlaceholder: "أدخل الرمز",
			pinHint: "استخدم رمز مكتب الاستقبال المخصص.",
			showPin: "إظهار الرمز",
			hidePin: "إخفاء الرمز",
			submit: "دخول",
			submitting: "جارٍ التحقق",
			loading: "جارٍ تحميل صفحة الدخول",
			invalid: "تعذر تسجيل الدخول. تحقق من الرمز وحاول مرة أخرى.",
			rateLimited: "محاولات كثيرة. انتظر قليلًا ثم حاول مرة أخرى.",
			noRegistration: "لا يتوفر تسجيل ذاتي.",
		},
		staff: {
			nav: {
				operations: "العمليات المباشرة",
				ownerArea: "مساحة المالك",
				accountRole: "مكتب الاستقبال",
			},
			live: {
				title: "العمليات المباشرة",
				open: "النادي مفتوح الآن",
				countLabel: "العدد الحالي التقريبي",
				capacityLabel: "السعة المضبوطة",
				crowdLabel: "حالة الازدحام",
				freshnessLabel: "آخر تحديث",
				freshnessLive: "تحديث مباشر",
				staleTitle: "بيانات الإشغال متأخرة",
				staleBody:
					"آخر قراءة معروفة ما زالت ظاهرة بوضوح. تحقّق من حالة جهاز العد قبل إجراء تصحيح.",
				offlineTitle: "جهاز العد غير متصل",
				offlineBody:
					"التحديث التلقائي متوقف. استخدم الإدخال المباشر فقط بعد التحقق من العدد.",
			},
			health: {
				title: "حالة النظام",
				counter: "جهاز العد",
				camera: "الكاميرا والبث",
				source: "مصدر القراءة",
				commands: "حالة الأوامر",
				lastSeen: "آخر اتصال",
				connected: "متصل",
				offline: "غير متصل",
				healthy: "يعمل بشكل طبيعي",
				degraded: "يحتاج إلى انتباه",
				automatic: "قراءة تلقائية",
				manual: "تقدير يدوي",
			},
			correction: {
				title: "أدوات تصحيح العدد",
				stepperLabel: "تعديل العدد",
				decrease: "إنقاص العدد",
				increase: "زيادة العدد",
				reasonLabel: "سبب مختصر (اختياري)",
				reasonPlaceholder: "اكتب سببًا مختصرًا",
				apply: "تطبيق التصحيح",
				applying: "جارٍ إرسال التصحيح",
				invalid: "أدخل عددًا صحيحًا لا يقل عن 0.",
			},
			directEntry: {
				label: "إدخال العدد مباشرة",
				help: "يُستخدم عند تعذر التحديث من جهاز العد وبعد التحقق من العدد.",
				inputLabel: "العدد التقريبي الحالي",
				apply: "اعتماد التقدير اليدوي",
				applying: "جارٍ اعتماد التقدير",
			},
			reset: {
				action: "إعادة الضبط إلى 0",
				title: "تأكيد إعادة الضبط",
				consequence: "سيتم ضبط العدد إلى 0 بعد التأكيد وتسجيل العملية.",
				cancel: "إلغاء",
				confirm: "تأكيد إعادة الضبط",
				confirming: "جارٍ إعادة الضبط",
			},
			command: {
				none: "لا توجد أوامر معلقة",
				pending: "الأمر قيد الانتظار",
				applied: "تم تطبيق الأمر",
				superseded: "استُبدل بأمر أحدث",
				failed: "تعذر إكمال الإجراء",
			},
			manualFallback: {
				title: "التقدير اليدوي نشط",
				body: "يظهر هذا التقدير مؤقتًا إلى أن يستعيد جهاز العد الاتصال ويطبّق التصحيح.",
				validFor: (minutes) => `صالح لمدة ${minutes} دقيقة من وقت الإدخال.`,
				reconnecting: "في انتظار عودة جهاز العد",
			},
		},
		owner: {
			nav: {
				operations: "العمليات المباشرة",
				analytics: "التحليلات",
				history: "السجل",
				settings: "الإعدادات",
				access: "إدارة الوصول",
				audit: "سجل التدقيق",
				health: "الصحة والتشغيل",
				accountRole: "المالك",
			},
			common: {
				loading: "جارٍ تحميل البيانات",
				empty: "لا توجد بيانات بعد",
				error: "تعذر تحميل البيانات",
				retry: "إعادة المحاولة",
				save: "حفظ التغييرات",
				saving: "جارٍ الحفظ",
				saved: "تم الحفظ",
				cancel: "إلغاء",
				confirm: "تأكيد",
			},
			analytics: {
				title: "تحليلات الإشغال",
				todayCurve: "منحنى الإشغال اليوم",
				curveSubtitle: "حسب يوم التشغيل وتوقيت النادي",
				yAxis: "الإشغال التقديري",
				xAxis: "الوقت",
				series: "الإشغال التقديري",
				capacityReference: (capacity) => `السعة المضبوطة: ${capacity}`,
				peak: "ذروة الإشغال التقديري",
				average: "متوسط الإشغال اليومي",
				crossings: "تقدير عبور المدخل اليومي",
				crossingsQualifier: "تقدير لعبور المدخل — وليس عدد أعضاء فريدين",
				dataTable: "بيانات المنحنى",
				viewTable: "عرض البيانات كجدول",
				hideTable: "إخفاء الجدول",
				time: "الوقت",
				occupancy: "الإشغال التقديري",
				percent: "النسبة من السعة",
				quality: "جودة البيانات",
				complete: "بيانات مكتملة",
				missing: "بيانات مفقودة",
				closed: "مغلق",
				dateRange: "النطاق الزمني",
				from: "من",
				to: "إلى",
				exportCsv: "تصدير CSV",
				exporting: "جارٍ تجهيز الملف",
				exportComplete: "تم تجهيز ملف CSV",
				empty: "لا توجد بيانات إشغال لهذا النطاق بعد.",
				error: "تعذر تحميل التحليلات. حاول مرة أخرى.",
			},
			history: {
				title: "سجل الإشغال",
				subtitle: "متوسط الإشغال حسب اليوم والساعة، بتوقيت النادي",
				busiestTimes: "الأوقات الأكثر ازدحامًا",
				heatmap: "متوسط الإشغال حسب اليوم والساعة",
				less: "أقل",
				more: "أكثر",
				closed: "مغلق",
				noData: "لا توجد بيانات",
				zero: "لا يوجد إشغال أثناء وقت الفتح",
				weeklyComparison: "المقارنة الأسبوعية",
				insufficientWeeks:
					"لا تتوفر مقارنة أسبوعية بعد. تظهر المقارنة بعد اكتمال أسبوعين من البيانات.",
				previousWeek: "الأسبوع السابق",
				currentWeek: "الأسبوع الحالي",
				peak: "ذروة الإشغال التقديري",
				average: "متوسط الإشغال اليومي",
				crossings: "تقدير عبور المدخل اليومي",
				crossingsQualifier: "تقدير لعبور المدخل — وليس عدد أعضاء فريدين",
				empty: "لم تُجمع بيانات تاريخية كافية بعد.",
				error: "تعذر تحميل سجل الإشغال. حاول مرة أخرى.",
			},
			settings: {
				title: "إعدادات النادي",
				description:
					"إدارة السعة وحدود الازدحام وساعات التشغيل ليأخذ كل تغيير أثره دون إعادة نشر.",
				capacity: "السعة المضبوطة",
				thresholds: "حدود مستويات الازدحام",
				quiet: "هادئ",
				moderate: "متوسط",
				busy: "مزدحم",
				packed: "ممتلئ جدًا",
				weeklyHours: "ساعات التشغيل الأسبوعية",
				day: "اليوم",
				openTime: "وقت الفتح",
				closeTime: "وقت الإغلاق",
				closedAllDay: "مغلق طوال اليوم",
				businessDayBoundary: "بداية يوم التشغيل",
				resetBuffer: "مهلة إعادة الضبط بعد الإغلاق",
				minutes: "دقيقة",
				timeZone: "توقيت النادي",
				invalidCapacity: "يجب أن تكون السعة عددًا صحيحًا أكبر من 0.",
				invalidThresholds: "يجب أن تكون الحدود مكتملة ومتزايدة دون تداخل.",
				invalidHours: "تحقق من ساعات الفتح والإغلاق.",
			},
			access: {
				title: "إدارة الوصول",
				description: "إدارة رمز مكتب الاستقبال وحسابات المالك المزوّدة مسبقًا.",
				staffPin: "رمز مكتب الاستقبال",
				staffPinStatus: "حالة الرمز",
				provisionPin: "إنشاء رمز",
				rotatePin: "تغيير الرمز",
				deactivatePin: "تعطيل الرمز",
				active: "نشط",
				inactive: "معطل",
				ownerAccounts: "حسابات المالك",
				account: "الحساب",
				role: "الدور",
				status: "الحالة",
				deactivateSessionNotice: "يُرفض وصول الجلسة المعطلة عند الطلب التالي.",
				confirmRotation: "سيصبح الرمز السابق غير صالح بعد التأكيد.",
			},
			audit: {
				title: "سجل التدقيق",
				description: "سجل زمني للتصحيحات وإعادة الضبط وتغييرات الإعدادات.",
				filter: "تصفية الإجراءات",
				allActions: "كل الإجراءات",
				correction: "تصحيح العدد",
				directEntry: "إدخال مباشر",
				reset: "إعادة ضبط",
				systemReset: "إعادة ضبط مجدولة",
				settingsChange: "تغيير الإعدادات",
				actor: "الجهة المنفذة",
				time: "الوقت",
				action: "الإجراء",
				from: "من",
				to: "إلى",
				reason: "السبب",
				noReason: "لم يُذكر سبب",
				frontDesk: "مكتب الاستقبال",
				owner: "المالك",
				system: "النظام",
				empty: "لا توجد إجراءات تطابق عوامل التصفية.",
			},
			health: {
				title: "الصحة والتشغيل",
				description: "ملخص فترات التوقف وحوادث جهاز العد والكاميرا والتنبيهات.",
				currentStatus: "الحالة الحالية",
				uptime: "مدة التشغيل",
				online: "متصل",
				offline: "غير متصل",
				incidents: "الحوادث",
				incidentType: "نوع الحادث",
				started: "بدأ",
				recovered: "تمت الاستعادة",
				duration: "المدة",
				counterSilence: "انقطاع تحديث جهاز العد",
				cameraFailure: "تعطل الكاميرا أو البث",
				processFailure: "تعطل عملية العد",
				lastSeen: "آخر اتصال",
				noIncidents: "لا توجد حوادث في النطاق المحدد.",
			},
		},
	},
	en: {
		global: {
			brand: "FITWAY",
			languageAction: "العربية",
			languageSwitchLabel: "Switch to Arabic",
			skip: "Skip to main content",
		},
		review: {
			title: "FITWAY review index",
			description:
				"Open every route, state, language, and viewport from one place.",
			publicGroup: "Public experience",
			staffGroup: "Staff operations",
			ownerGroup: "Owner area",
			route: "Route",
			state: "State",
			language: "Language",
			viewport: "Viewport",
			open: "Open screen",
			live: "Live",
			loading: "Loading",
			stale: "Delayed",
			unavailable: "Unavailable",
			closed: "Closed",
			error: "Error",
			login: "Staff login",
			staffLive: "Live operations",
			analytics: "Analytics",
			history: "History",
			settings: "Settings",
			access: "Access management",
			audit: "Audit log",
			health: "Health and uptime",
			desktop: "Desktop",
			tablet: "Tablet",
			mobile: "Mobile",
		},
		public: {
			bands: {
				quiet: "Quiet",
				moderate: "Moderate",
				busy: "Busy",
				packed: "Packed",
			},
			live: {
				open: "Gym open now",
				freshness: "Live update",
				updated: "Updated 2:59 PM",
				relative: "30 seconds ago",
				combinedFreshness: "Live update · Updated 2:59 PM · 30 seconds ago",
				crowdLabel: "Crowd level",
				crowdValue: "Moderate",
				countLabel: "Approximate count",
				currentLevel: "Current level",
				signalLabel: "Crowd-level signal",
				signalSummary:
					"The current crowd level is Moderate. Quiet has been reached, Moderate is current, and higher levels are pending.",
				summary:
					"The gym is open now. Crowd level: Moderate. Approximate count: 37. Live update. Updated 2:59 PM, 30 seconds ago.",
			},
			loading: {
				label: "Loading gym status",
				summary: "Loading the latest gym status.",
			},
			stale: {
				status: "Live updates are delayed",
				crowdLabel: "Last known crowd level",
				countLabel: "Last known approximate count",
				freshness: "Last known update",
				updated: "Last known update 3:00 PM",
				relative: "5 minutes ago",
				warning: (count, time) =>
					`The last known approximate count was ${count} at ${time}. Live updates are delayed.`,
				summary: (band, count, time) =>
					`Live updates are delayed. Last known crowd level: ${band}. Last known approximate count: ${count}. Last updated ${time}.`,
			},
			unavailable: {
				eyebrow: "Gym status now",
				title: "Live occupancy is unavailable right now",
				body: "We do not show an old count as live. Please try again later.",
				summary: "No reliable occupancy information is available right now.",
			},
			closed: {
				status: "Closed now",
				title: "Closed now",
				opensAt: (time) => `Opens ${time}`,
				summary: (time) => `The gym is closed now. Opens today at ${time}.`,
			},
			error: {
				eyebrow: "Gym status now",
				title: "We could not load the gym status",
				body: "Something went wrong while fetching the latest status. Try again.",
				retry: "Try again",
				retrying: "Trying again",
				summary:
					"The gym status could not be loaded. A retry option is available.",
			},
		},
		login: {
			title: "Front desk access",
			description: "Enter the shared access PIN to open live operations.",
			pinLabel: "Access PIN",
			pinPlaceholder: "Enter PIN",
			pinHint: "Use the assigned front desk PIN.",
			showPin: "Show PIN",
			hidePin: "Hide PIN",
			submit: "Continue",
			submitting: "Verifying",
			loading: "Loading staff access",
			invalid: "Sign-in failed. Check the PIN and try again.",
			rateLimited: "Too many attempts. Wait a moment and try again.",
			noRegistration: "Self-registration is not available.",
		},
		staff: {
			nav: {
				operations: "Live operations",
				ownerArea: "Owner area",
				accountRole: "Front desk",
			},
			live: {
				title: "Live operations",
				open: "Gym open now",
				countLabel: "Current approximate count",
				capacityLabel: "Configured capacity",
				crowdLabel: "Crowd status",
				freshnessLabel: "Last update",
				freshnessLive: "Live update",
				staleTitle: "Occupancy data is delayed",
				staleBody:
					"The last known reading remains clearly labeled. Check counter health before correcting it.",
				offlineTitle: "The counting device is offline",
				offlineBody:
					"Automatic updates have stopped. Use direct entry only after checking the count.",
			},
			health: {
				title: "System health",
				counter: "Counting device",
				camera: "Camera and feed",
				source: "Reading source",
				commands: "Command status",
				lastSeen: "Last seen",
				connected: "Connected",
				offline: "Offline",
				healthy: "Operating normally",
				degraded: "Needs attention",
				automatic: "Automatic reading",
				manual: "Manual estimate",
			},
			correction: {
				title: "Count correction tools",
				stepperLabel: "Adjust count",
				decrease: "Decrease count",
				increase: "Increase count",
				reasonLabel: "Short reason (optional)",
				reasonPlaceholder: "Add a short reason",
				apply: "Apply correction",
				applying: "Sending correction",
				invalid: "Enter a whole number of 0 or more.",
			},
			directEntry: {
				label: "Enter the count directly",
				help: "Use this when the counting device cannot update, after checking the count.",
				inputLabel: "Current approximate count",
				apply: "Use manual estimate",
				applying: "Saving manual estimate",
			},
			reset: {
				action: "Reset to 0",
				title: "Confirm reset",
				consequence:
					"The count will be set to 0 after confirmation and the action will be recorded.",
				cancel: "Cancel",
				confirm: "Confirm reset",
				confirming: "Resetting",
			},
			command: {
				none: "No pending commands",
				pending: "Command pending",
				applied: "Command applied",
				superseded: "Replaced by a newer command",
				failed: "Action could not be completed",
			},
			manualFallback: {
				title: "Manual estimate is active",
				body: "This estimate remains temporary until the counting device reconnects and applies the correction.",
				validFor: (minutes) => `Valid for ${minutes} minutes from entry.`,
				reconnecting: "Waiting for the counting device to reconnect",
			},
		},
		owner: {
			nav: {
				operations: "Live operations",
				analytics: "Analytics",
				history: "History",
				settings: "Settings",
				access: "Access management",
				audit: "Audit log",
				health: "Health and uptime",
				accountRole: "Owner",
			},
			common: {
				loading: "Loading data",
				empty: "No data yet",
				error: "Data could not be loaded",
				retry: "Try again",
				save: "Save changes",
				saving: "Saving",
				saved: "Saved",
				cancel: "Cancel",
				confirm: "Confirm",
			},
			analytics: {
				title: "Occupancy analytics",
				todayCurve: "Today's occupancy curve",
				curveSubtitle: "Based on the gym business day and local time",
				yAxis: "Approximate occupancy",
				xAxis: "Time",
				series: "Approximate occupancy",
				capacityReference: (capacity) => `Configured capacity: ${capacity}`,
				peak: "Peak approximate occupancy",
				average: "Daily average occupancy",
				crossings: "Estimated daily entrance crossings",
				crossingsQualifier: "Estimated entrance crossings, not unique members",
				dataTable: "Curve data",
				viewTable: "View data as a table",
				hideTable: "Hide data table",
				time: "Time",
				occupancy: "Approximate occupancy",
				percent: "Percent of capacity",
				quality: "Data quality",
				complete: "Complete data",
				missing: "Missing data",
				closed: "Closed",
				dateRange: "Date range",
				from: "From",
				to: "To",
				exportCsv: "Export CSV",
				exporting: "Preparing file",
				exportComplete: "CSV file is ready",
				empty: "No occupancy data is available for this range yet.",
				error: "Analytics could not be loaded. Try again.",
			},
			history: {
				title: "Occupancy history",
				subtitle: "Average occupancy by day and hour in gym local time",
				busiestTimes: "Busiest times",
				heatmap: "Average occupancy by day and hour",
				less: "Less",
				more: "More",
				closed: "Closed",
				noData: "No data",
				zero: "No occupancy while open",
				weeklyComparison: "Week-over-week comparison",
				insufficientWeeks:
					"A weekly comparison is not available yet. It appears after two complete weeks of data.",
				previousWeek: "Previous week",
				currentWeek: "Current week",
				peak: "Peak approximate occupancy",
				average: "Daily average occupancy",
				crossings: "Estimated daily entrance crossings",
				crossingsQualifier: "Estimated entrance crossings, not unique members",
				empty: "There is not enough historical data yet.",
				error: "Occupancy history could not be loaded. Try again.",
			},
			settings: {
				title: "Gym settings",
				description:
					"Manage capacity, crowd thresholds, and operating hours without redeploying.",
				capacity: "Configured capacity",
				thresholds: "Crowd-level thresholds",
				quiet: "Quiet",
				moderate: "Moderate",
				busy: "Busy",
				packed: "Packed",
				weeklyHours: "Weekly operating hours",
				day: "Day",
				openTime: "Opening time",
				closeTime: "Closing time",
				closedAllDay: "Closed all day",
				businessDayBoundary: "Business-day boundary",
				resetBuffer: "Post-close reset buffer",
				minutes: "minutes",
				timeZone: "Gym time zone",
				invalidCapacity: "Capacity must be a whole number greater than 0.",
				invalidThresholds:
					"Thresholds must be complete, increasing, and non-overlapping.",
				invalidHours: "Check the opening and closing times.",
			},
			access: {
				title: "Access management",
				description:
					"Manage the front desk PIN and separately provisioned owner accounts.",
				staffPin: "Front desk PIN",
				staffPinStatus: "PIN status",
				provisionPin: "Create PIN",
				rotatePin: "Rotate PIN",
				deactivatePin: "Deactivate PIN",
				active: "Active",
				inactive: "Inactive",
				ownerAccounts: "Owner accounts",
				account: "Account",
				role: "Role",
				status: "Status",
				deactivateSessionNotice:
					"A deactivated session is rejected on its next request.",
				confirmRotation:
					"The previous PIN will stop working after confirmation.",
			},
			audit: {
				title: "Audit log",
				description:
					"A chronological record of corrections, resets, and settings changes.",
				filter: "Filter actions",
				allActions: "All actions",
				correction: "Count correction",
				directEntry: "Direct entry",
				reset: "Reset",
				systemReset: "Scheduled reset",
				settingsChange: "Settings change",
				actor: "Actor",
				time: "Time",
				action: "Action",
				from: "From",
				to: "To",
				reason: "Reason",
				noReason: "No reason provided",
				frontDesk: "Front desk",
				owner: "Owner",
				system: "System",
				empty: "No actions match these filters.",
			},
			health: {
				title: "Health and uptime",
				description:
					"A summary of downtime, counter and camera incidents, and alerts.",
				currentStatus: "Current status",
				uptime: "Uptime",
				online: "Online",
				offline: "Offline",
				incidents: "Incidents",
				incidentType: "Incident type",
				started: "Started",
				recovered: "Recovered",
				duration: "Duration",
				counterSilence: "Counting-device update gap",
				cameraFailure: "Camera or feed failure",
				processFailure: "Counting-process failure",
				lastSeen: "Last seen",
				noIncidents: "There are no incidents in the selected range.",
			},
		},
	},
};

const moderateSignal = {
	quiet: "complete",
	moderate: "current",
	busy: "inactive",
	packed: "inactive",
};

export const publicFixtures = {
	live: {
		state: "live",
		freshness: "fresh",
		open: true,
		band: "moderate",
		count: "37",
		timeZone: "Asia/Riyadh",
		lastUpdatedAt: "2026-07-17T11:59:30.000Z",
		computedAt: "2026-07-17T12:00:00.000Z",
		time: { ar: "2:59 م", en: "2:59 PM" },
		relative: { ar: "قبل 30 ثانية", en: "30 seconds ago" },
		signal: moderateSignal,
	},
	loading: {
		state: "loading",
	},
	stale: {
		state: "stale",
		freshness: "stale",
		open: true,
		band: "moderate",
		count: "37",
		timeZone: "Asia/Riyadh",
		lastUpdatedAt: "2026-07-17T12:00:00.000Z",
		computedAt: "2026-07-17T12:05:00.000Z",
		time: { ar: "3:00 م", en: "3:00 PM" },
		relative: { ar: "قبل 5 دقائق", en: "5 minutes ago" },
		signal: moderateSignal,
	},
	unavailable: {
		state: "unavailable",
		freshness: "unavailable",
	},
	closed: {
		state: "closed",
		freshness: "closed",
		open: false,
		timeZone: "Asia/Riyadh",
		nextOpenAt: "2026-07-17T11:00:00.000Z",
		nextOpenTime: { ar: "2:00 م", en: "2:00 PM" },
	},
	error: {
		state: "error",
		recoverable: true,
	},
};

export const staffFixtures = {
	live: {
		state: "live",
		open: true,
		band: "moderate",
		count: "37",
		capacity: "100",
		timeZone: "Asia/Riyadh",
		lastUpdatedAt: "2026-07-17T11:59:30.000Z",
		time: { ar: "2:59 م", en: "2:59 PM" },
		relative: { ar: "قبل 30 ثانية", en: "30 seconds ago" },
		source: "automatic",
		health: { counter: "connected", camera: "healthy" },
		command: "none",
	},
	stale: {
		state: "stale",
		open: true,
		band: "moderate",
		count: "37",
		capacity: "100",
		timeZone: "Asia/Riyadh",
		lastUpdatedAt: "2026-07-17T12:00:00.000Z",
		time: { ar: "3:00 م", en: "3:00 PM" },
		relative: { ar: "قبل 5 دقائق", en: "5 minutes ago" },
		source: "automatic",
		health: { counter: "offline", camera: "degraded" },
		command: "none",
	},
	offline: {
		state: "offline",
		open: true,
		capacity: "100",
		source: "automatic",
		health: { counter: "offline", camera: "degraded" },
		command: "none",
	},
	pending: {
		state: "pending",
		open: true,
		band: "moderate",
		count: "37",
		targetCount: "40",
		capacity: "100",
		source: "automatic",
		health: { counter: "connected", camera: "healthy" },
		command: "pending",
	},
	manualFallback: {
		state: "manualFallback",
		open: true,
		band: "moderate",
		count: "40",
		capacity: "100",
		timeZone: "Asia/Riyadh",
		lastUpdatedAt: "2026-07-17T12:05:00.000Z",
		time: { ar: "3:05 م", en: "3:05 PM" },
		validForMinutes: "30",
		source: "manual",
		health: { counter: "offline", camera: "degraded" },
		command: "pending",
	},
};

export const analyticsFixture = {
	timeZone: "Asia/Riyadh",
	businessDate: "2026-07-16",
	capacity: "100",
	series: [
		{
			time: { ar: "6:00 ص", en: "6:00 AM" },
			count: "8",
			percent: "8",
			quality: "complete",
		},
		{
			time: { ar: "8:00 ص", en: "8:00 AM" },
			count: "19",
			percent: "19",
			quality: "complete",
		},
		{
			time: { ar: "10:00 ص", en: "10:00 AM" },
			count: "31",
			percent: "31",
			quality: "complete",
		},
		{
			time: { ar: "12:00 م", en: "12:00 PM" },
			count: "44",
			percent: "44",
			quality: "complete",
		},
		{
			time: { ar: "2:00 م", en: "2:00 PM" },
			count: "52",
			percent: "52",
			quality: "complete",
		},
		{
			time: { ar: "4:00 م", en: "4:00 PM" },
			count: "68",
			percent: "68",
			quality: "complete",
		},
		{
			time: { ar: "6:00 م", en: "6:00 PM" },
			count: "79",
			percent: "79",
			quality: "complete",
		},
		{
			time: { ar: "8:00 م", en: "8:00 PM" },
			count: "84",
			percent: "84",
			quality: "complete",
		},
		{
			time: { ar: "10:00 م", en: "10:00 PM" },
			count: "66",
			percent: "66",
			quality: "complete",
		},
		{
			time: { ar: "12:00 ص", en: "12:00 AM" },
			count: "39",
			percent: "39",
			quality: "complete",
		},
		{
			time: { ar: "1:30 ص", en: "1:30 AM" },
			count: "18",
			percent: "18",
			quality: "complete",
		},
	],
	summary: {
		peakCount: "84",
		peakTime: { ar: "8:00 م", en: "8:00 PM" },
		averageCount: "46",
		estimatedCrossings: "310",
	},
};

export const historyFixture = {
	timeZone: "Asia/Riyadh",
	range: { from: "2026-07-04", to: "2026-07-17" },
	capacity: "100",
	hours: ["6", "8", "10", "12", "14", "16", "18", "20", "22", "00", "02"],
	days: [
		{
			key: "saturday",
			label: { ar: "السبت", en: "Saturday" },
			values: [
				"18",
				"26",
				"34",
				"42",
				"49",
				"61",
				"70",
				"82",
				"64",
				"38",
				"20",
			],
		},
		{
			key: "sunday",
			label: { ar: "الأحد", en: "Sunday" },
			values: [
				"12",
				"20",
				"29",
				"38",
				"45",
				"55",
				"68",
				"76",
				"58",
				"32",
				"16",
			],
		},
		{
			key: "monday",
			label: { ar: "الاثنين", en: "Monday" },
			values: [
				"10",
				"18",
				"28",
				"36",
				"44",
				"57",
				"72",
				"80",
				"61",
				"35",
				"17",
			],
		},
		{
			key: "tuesday",
			label: { ar: "الثلاثاء", en: "Tuesday" },
			values: [
				"11",
				"19",
				"27",
				"35",
				"43",
				"59",
				"74",
				"83",
				"63",
				"37",
				"18",
			],
		},
		{
			key: "wednesday",
			label: { ar: "الأربعاء", en: "Wednesday" },
			values: [
				"13",
				"21",
				"30",
				"39",
				"47",
				"60",
				"75",
				"81",
				"62",
				"36",
				"17",
			],
		},
		{
			key: "thursday",
			label: { ar: "الخميس", en: "Thursday" },
			values: [
				"16",
				"25",
				"35",
				"44",
				"52",
				"68",
				"79",
				"84",
				"66",
				"39",
				"18",
			],
		},
		{
			key: "friday",
			label: { ar: "الجمعة", en: "Friday" },
			values: [
				null,
				null,
				"14",
				"22",
				"31",
				"45",
				"58",
				"69",
				"54",
				"30",
				"15",
			],
		},
	],
	summary: {
		peakCount: "84",
		peakDay: { ar: "الخميس", en: "Thursday" },
		peakTime: { ar: "8:00 م", en: "8:00 PM" },
		averageCount: "46",
		estimatedCrossings: "310",
	},
	weekComparison: {
		weeksAvailable: "1",
		status: "insufficient",
		current: null,
		previous: null,
	},
};
